# Generated by Django 3.1.5 on 2021-01-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_onsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gallery',
            field=models.ImageField(default='https://redzonekickboxing.com/wp-content/uploads/2017/04/default-image-620x600.jpg', upload_to=None),
        ),
    ]
